import{a as S,S as b,i as s}from"./assets/vendor--6n4cVRZ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const q="54652097-fa33845d90f17562231f3e558",B="https://pixabay.com/api/";async function m(a,t){return(await S.get(B,{params:{key:q,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const y=document.querySelector(".gallery"),p=document.querySelector(".load-more"),g=document.querySelector(".loader");let E=new b(".gallery a");function h(a){const t=a.map(o=>`
      <li class="gallery-item">
        <a href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" />
        </a>
        <div class="info">
          <p>Likes: ${o.likes}</p>
          <p>Views: ${o.views}</p>
          <p>Comments: ${o.comments}</p>
          <p>Downloads: ${o.downloads}</p>
        </div>
      </li>`).join("");y.insertAdjacentHTML("beforeend",t),E.refresh()}function $(){y.innerHTML=""}function L(){g.classList.add("active")}function u(){g.classList.remove("active")}function w(){p.classList.add("active")}function c(){p.classList.remove("active")}const f=document.querySelector(".form"),M=document.querySelector(".load-more");let i="",n=1,v=0;f.addEventListener("submit",async a=>{if(a.preventDefault(),i=f.elements["search-text"].value.trim(),!i){s.warning({title:"Warning",message:"Please enter a search term"});return}$(),n=1,c(),L(),c();try{const t=await m(i,n);v=t.totalHits,t.hits.length===0?s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}):setTimeout(()=>{h(t.hits),w(),u()},1e3)}catch{s.error({title:"Error",message:"Something went wrong. Try again later."})}finally{u()}});M.addEventListener("click",async()=>{n+=1,L(),c();try{const a=await m(i,n);setTimeout(()=>{h(a.hits);const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),w(),u()},1e3),n*15>=v&&(c(),s.info({title:"Info",message:"We're sorry, but you've reached the end of search result."}))}catch{s.error({title:"Error",message:"Something went wrong."})}finally{}});
//# sourceMappingURL=index.js.map
