import{a as S,S as b,i as n}from"./assets/vendor--6n4cVRZ.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const q="54652097-fa33845d90f17562231f3e558",B="https://pixabay.com/api/";async function m(s,e){return(await S.get(B,{params:{key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}const y=document.querySelector(".gallery"),h=document.querySelector(".load-more"),p=document.querySelector(".loader");let E=new b(".gallery a");function g(s){const e=s.map(r=>`
      <li class="gallery-item">
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="info">
          <p>Likes: ${r.likes}</p>
          <p>Views: ${r.views}</p>
          <p>Comments: ${r.comments}</p>
          <p>Downloads: ${r.downloads}</p>
        </div>
      </li>`).join("");y.insertAdjacentHTML("beforeend",e),E.refresh()}function $(){y.innerHTML=""}function L(){p.classList.add("active")}function w(){p.classList.remove("active")}function v(){h.classList.add("active")}function a(){h.classList.remove("active")}const f=document.querySelector(".form"),I=document.querySelector(".load-more");let l="",i=1,d=0;f.addEventListener("submit",async s=>{if(s.preventDefault(),l=f.elements["search-text"].value.trim(),!l){n.warning({title:"Warning",message:"Please enter a search term"});return}$(),i=1,a(),L();try{const e=await m(l,i);d=e.totalHits,e.hits.length===0?(n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),a()):(g(e.hits),d<=15?(a(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search result."})):v())}catch{n.error({title:"Error",message:"Something went wrong. Try again later."}),a()}finally{w()}});I.addEventListener("click",async()=>{i+=1,L(),a();try{const s=await m(l,i);g(s.hits);const e=document.querySelector(".gallery-item:last-child");if(e){const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}i*15>=d?(a(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search result."})):v()}catch{n.error({title:"Error",message:"Something went wrong."}),a()}finally{w()}});
//# sourceMappingURL=index.js.map
